In [1]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [7]:
import numpy as np
arr = np.array(a)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape) # output = (3, 3). Indicates 3 rows and 3 columns

print(arr.size) # multiple all values of shape: 3*3 = 9

print(arr[0][0])
print(arr[1][1])
arr[0][0] = -1
print(arr[0][0])



[[11 12 13]
 [21 22 23]
 [31 32 33]]
<class 'numpy.ndarray'>
int64
(3, 3)
9
11
22
-1


In [12]:
# slicing
print(arr , "\n")

print( arr[0, 0:2] ) # print the first 2 values of 0th row
print( arr[0:2, 1] ) # print the first 2 values of 1st column

print( arr[0:2, 0:2] ) # print the first 2 rows of the first 2 columns

[[-1 12 13]
 [21 22 23]
 [31 32 33]] 

[-1 12]
[12 22]
[[-1 12]
 [21 22]]


## Basic Mathematical Operations


In [17]:
x = np.array([[1, 0], [0, 1]]) 

y = np.array([[2, 1], [1, 2]]) 

z = x+y
print(z)
z = x-y
print(z)
z = x*y
print(z)
z = x/y
print(z)



[[3 1]
 [1 3]]
[[-1 -1]
 [-1 -1]]
[[2 0]
 [0 2]]
[[0.5 0. ]
 [0.  0.5]]


In [21]:
x = np.array([[0, 1, 1], [1, 0, 1]])

y = np.array([[1, 1], [1, 1], [-1, 1]])

# dor product does the matrix multiplication
z = np.dot(x,y)
print(z)

print(np.sin(z))

# print transpose
print(z.T)

[[0 2]
 [0 2]]
[[0.         0.90929743]
 [0.         0.90929743]]
[[0 0]
 [2 2]]
